Web 6 contributors section update
Samoa-Stack-Overflow/sso-website pull request #31
Opened 2024-02-04 21:17 UTC by renaldox

# Describe your changes
updating branch with all changes
## Issue ticket number and link

## Checklist before requesting a review

- [x ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2024-02-04 21:35 UTC, westerandr commented
Uso can you pull latest changes from main please? and include your component with the rest in page.svelte

2024-02-04 21:37 UTC, westerandr commented
But overall looks good! Might need you to work on different colors for dark  and light mode for the cards. Looks good on mobile, might need to reduce space between cards. Good stuff!

2024-02-04 22:04 UTC, Green-Ranger11 commented
Also don't forget to import and showcase your changes in the `+page.svelte` file!

2024-02-05 09:30 UTC, westerandr commented
Also don't forget to reference the issue number in your PR description.

2024-02-07 03:50 UTC, Green-Ranger11 requested changes
Just one small change and should be good to go!

2024-02-07 03:50 UTC, Green-Ranger11 commented on src/lib/Components/Contributors.svelte
Hol up we gotta put this in `/components` lowercase please haha

2024-02-07 03:50 UTC, Green-Ranger11 requested changes
Just one small change and should be good to go!

2024-02-07 08:59 UTC, Green-Ranger11 approved these changes
LGTM! Malo lava!

2024-02-07 09:01 UTC, merged