re-organize sections
Samoa-Stack-Overflow/sso-website pull request #48
Opened 2024-02-17 05:36 UTC by tausani-ah-chong

# Describe your changes

Re-organize sections

- Swapped order of `Contact` with `Contributors`

## Issue ticket number and link

https://github.com/Samoa-Stack-Overflow/sso-website/issues/33

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2024-02-17 05:53 UTC, westerandr requested changes
Malo uso! Looks good 🙂 

Just one small addition please, are you able to swap the contributors and reach out links on the nav bar 🙏

2024-02-17 11:28 UTC, tausani-ah-chong commented
@westerandr Seki I can make that change!

A couple things I took the liberty to do extra while making the change:

1. Can I suggest renaming "Reach out" to "Contact Us". I feel is more consistent with code + the copy in the UI
2. I noticed the 'About' section was missing in the nav bar, so Ive added in. But I also don't have context, and there might be a reason why it wasn't there. Happy to remove if intentionally not there.
3. I created a `SectionName` key value pair, as I noticed when I swapped the `Contributors` & `Contact` in `menuItems` the refs were named `section1`, `section2`, `section3`... and thought having `SectionName` is more explicit and bug prone

Thanks for reviewing uso!

2024-02-17 11:30 UTC, tausani-ah-chong commented on src/lib/utils/menuItems.js
> +}
Refer to point 3

Explicit naming

2024-02-17 11:30 UTC, tausani-ah-chong commented on src/lib/utils/menuItems.js
> +    name: 'Contact Us',
Refer to point 1.

Renamed to "Contact Us" for consistency

2024-02-17 11:30 UTC, tausani-ah-chong commented on src/lib/utils/menuItems.js
> +    name: 'About',
Refer to point 2.

Was missing in nav bar

2024-02-17 11:50 UTC, tausani-ah-chong commented on src/lib/utils/menuItems.js
>      icon: IconCar
I also noticed that every item as the same icon `IconCar`

Ive [created an issue](https://github.com/Samoa-Stack-Overflow/sso-website/issues/49) for this to be addressed if need be. 

For now I won't bloat the PR even more than it needs to be

2024-02-18 22:50 UTC, westerandr approved these changes

2024-02-18 22:51 UTC, westerandr commented
LGTM uso! Thanks for contributing 🤝

2024-02-18 22:51 UTC, merged